### PR TITLE
Make the servers with no citizens available in the public authorized page

### LINKED ISSUE #5: Feature Enhancement: Clean up verbiage on the "Edit Citizens" page
"Anyone can join" is misleading.  

If the Citizens Editor is blank, anyone can connect from the outside if they have the hostname and port.  However, the worlds will not appear in everyone's PhValheim library.  

I'm considering adding a "public" checkbox that will allow anyone to join *and* the world will appear in the public library interface for all authenticated users.

### LINKED ISSUE #26: listing none on citizens page dosent work
continues to not let anyone join

### PR DESCRIPTION
**Pull request by Swesen**
As the edit citizen page states that anyone should be able to join if left empty, one would expect the public authorized page to show these worlds.

resolves #5
resolves #26

### CODE REVIEW

**Comment by brianmiller** [comment]
Thank you for the merge request.  Your change doesn't seem to work with NULL values.  Selecting by NULL also doesn't seem to work.  If I manually add a blank value to an existing world, then the select "" query works.

Maybe we need to adjust the language on the citizens page and simply add a public checkbox.

**Comment by Swesen** [comment]
Ok, so citizens start out as NULL and if you edit the citizens it turns into an empty string because that is what my server has. Having a seperate bool for making a world public would make it so you have to set this to empty and set it public, or would setting it public bypass the permittedlist.txt?

**Comment by brianmiller** [comment]
Setting the world to public would make the world visible to everyone and wipe the permit list on start.

**Comment by brianmiller** [comment]
I'm almost done with the changes.  I should have an RC tag ready in 20-30 minutes.

**Comment by brianmiller** [comment]
2.19 rc is building now

**Comment by brianmiller** [comment]
nice work--I didn't release we were both working on the changes :)

**Comment by brianmiller** [comment]
I've validated 2.19 and the latest tag has been pushed.  We should have full public capability now.

**Comment by brianmiller** [comment]
@Swesen consider joining our Discord https://discord.gg/8RMMrJVQgy

It looks like you're more than capable of contributing to the project. 👍

**Pull request closed without merging**
